### ISSUE TITLE
AttributeError: 'str' object has no attribute 'start

### ISSUE THREAD

**Issue by ifiddes-10x** [nspies/svviz2#48]
I think there is some version mismatch issues between `genomeview` and `svviz2`. When I installed `svviz2` and ran it, I got the following error:

```
Traceback (most recent call last):
  File "/mnt/home/ian/anaconda3/bin/svviz2", line 11, in <module>
    load_entry_point('svviz2', 'console_scripts', 'svviz2')()
  File "/mnt/home/ian/svviz2/src/svviz2/app/main.py", line 60, in main
    run(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/app/main.py", line 46, in run
    visualize.visualize(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/visualize/visualize.py", line 58, in visualize
    _visualize(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/visualize/visualize.py", line 76, in _visualize
    genome_view = GenomeView(part.id, start, end, "+", source, name=part.id)
TypeError: __init__() got multiple values for argument 'name'
```

Looking at the code led me to uninstall the pypi version of `genomeview` and install the current git master -- it seems like the API for `GenomeView` changed. However, now that I am on current git master for both, I get the following:

```
Traceback (most recent call last):
  File "/mnt/home/ian/anaconda3/bin/svviz2", line 11, in <module>
    load_entry_point('svviz2', 'console_scripts', 'svviz2')()
  File "/mnt/home/ian/svviz2/src/svviz2/app/main.py", line 60, in main
    run(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/app/main.py", line 46, in run
    visualize.visualize(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/visualize/visualize.py", line 58, in visualize
    _visualize(datahub)
  File "/mnt/home/ian/svviz2/src/svviz2/visualize/visualize.py", line 103, in _visualize
    export.export(doc, datahub, context)
  File "/mnt/home/ian/svviz2/src/svviz2/io/export.py", line 28, in export
    for l in sv_document.render():
  File "/mnt/home/ian/genomeview/genomeview/genomeview.py", line 39, in render
    self.layout()
  File "/mnt/home/ian/genomeview/genomeview/genomeview.py", line 36, in layout
    element.layout(self.view_width)
  File "/mnt/home/ian/genomeview/genomeview/genomeview.py", line 84, in layout
    view.layout(self.each_width)
  File "/mnt/home/ian/genomeview/genomeview/genomeview.py", line 123, in layout
    track.layout(self.scale)
  File "/mnt/home/ian/genomeview/genomeview/intervaltrack.py", line 75, in layout
    self.layout_interval(interval)
  File "/mnt/home/ian/genomeview/genomeview/intervaltrack.py", line 51, in layout_interval
    interval_start = self.scale.topixels(interval.start)
AttributeError: 'str' object has no attribute 'start'
```

I also am unable to install `rsvg-convert` or `inkscape` easily on remote machines that have the actual large BAM files I want to investigate. Are these required? The documentation is not clear to me.

**Comment by nspies** [comment]
Thanks for your bug report! I think I've fixed this in the latest version of svviz2 on github -- please let me know if it works for you now.
