### ISSUE TITLE
ssw not available

### ISSUE THREAD

**Issue by frankbioinfo** [nspies/svviz2#56]
Hi @nspies 

Thank you for developing this tool, i tried installing this and using it with `--aligner ssw` very first line after execution is `ssw library not found` and the program quits with this error `NameError: name 'ssw_wrap' is not defined` , what surprises me is svviz (not svviz2) works fine which i believe also uses ssw. 

Wondering what am i missing to install.

Thanks
Frank

**Comment by nspies** [comment]
Hrm, let me look into this. You're right, installing ssw using svviz1 should be sufficient for supplying this to svviz2.

**Comment by nspies** [comment]
PS I think the bwa aligner is likely to be better than ssw in most, if not all, cases, though the best way to verify this in your particular use case would be to run svviz2 with both options and compare the results.

**Comment by nspies** [comment]
Ah, thanks for the clarification. Because ssw is optional for svviz2, installing svviz2 doesn’t result in ssw being installed. The easiest way to install ssw is to install svviz1 into the same docker where you’re installing and running svviz2.

**Comment by frankbioinfo** [comment]
@nspies sorry to report back that adding both versions in same docker did not fix the issue, just noticed you cannot load ssw too, looked at the readme.md (usage) snapshot for svviz2, also keep seeing this error should i open this as new issue?

Any thoughts..

```
2018-10-29 17:34:11 - svviz2.app.sample         - INFO  - Calculating read statistics for try1.bam
2018-10-29 17:39:39 - svviz2.io.readstatistics  - INFO  -   counts +/-:0      -/+:0      +/+:0      -/-:0      unpaired:0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/sample.py", line 65, in _load
    with open(stats_file_path) as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/svviz2_out/try1.bam.svviz_stats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/svviz2", line 11, in <module>
    load_entry_point('svviz2==2.0a3', 'console_scripts', 'svviz2')()
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/main.py", line 59, in main
    datahub = get_datahub()
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/main.py", line 21, in get_datahub
    datahub.set_args(args)
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/datahub.py", line 268, in set_args
    sample = Sample(name, bam_path, self, extra_args)
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/sample.py", line 57, in __init__
    self._load(extra_args)
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/sample.py", line 78, in _load
    self._load_from_bam(extra_args)
  File "/usr/local/lib/python3.6/site-packages/svviz2/app/sample.py", line 97, in _load_from_bam
    self.read_statistics = ReadStatistics(self.bam)
  File "/usr/local/lib/python3.6/site-packages/svviz2/io/readstatistics.py", line 30, in __init__
    results = sampleInsertSizes(bam)
  File "/usr/local/lib/python3.6/site-packages/svviz2/io/readstatistics.py", line 279, in sampleInsertSizes
    chosenOrientations = chooseOrientation(orientations)
  File "/usr/local/lib/python3.6/site-packages/svviz2/io/readstatistics.py", line 154, in chooseOrientation
    chosenOrientations = [ranked.pop()]
IndexError: pop from empty list```

Many thanks

**Comment by frankbioinfo** [comment]
Installing svviz1 in the same image helped thanks.
