### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by moldach** [nspies/svviz2#62]
I'm getting an unknown error when trying to run `svviz2` on a shared-academic HPC. I believe that I have all the dependencies installed referenced in `PATH`.

### Load modules/environment

```
module load nixpkgs/16.09
module load trf/4.09
module load scipy-stack
module load bwa/0.7.17
module load gcc/7.3.0
module load r/3.6.1
pip install rpy2
pip install -U git+git://github.com/nspies/svviz2.git
```

### Run `svviz2`

```
ssw library not found
2020-03-18 22:36:54 - svviz2.app.sample         - INFO  - Loaded pre-computed read statistics for N2_trim_bwaMEM_sort_dedupped
2020-03-18 22:36:54 - svviz2.app.main           - INFO  - Search distance: 614bp
2020-03-18 22:36:54 - svviz2.app.main           - INFO  - Align distance: 847bp
[W::vcf_parse] Contig 'I' is not defined in the header. (Quick workaround: index the file with tabix.)
2020-03-18 22:36:54 - svviz2.io.vcfparser       - WARNING - Only tandem duplications are supported; if this duplication is in fact a tandem duplication, make sure that the alt field of the vcf record is '<DUP:TANDEM>': I    4341001 N2_CNVnator_dup_1  N<DUP>   .       PASS    END=4357000;SVTYPE=DUP;SVLEN=16000;IMPRECISE;natorRD=2.36251;natorP1=1.53711e-06;natorP2=0;natorP3=3.93758e-05;natorP4=0;natorQ0=0.977525

2020-03-18 22:36:54 - svviz2.io.vcfparser       - WARNING - Only tandem duplications are supported; if this duplication is in fact a tandem duplication, make sure that the alt field of the vcf record is '<DUP:TANDEM>': I    10204001        N2_CNVnator_dup_2   N       <DUP>   .       PASS    END=10220000;SVTYPE=DUP;SVLEN=16000;IMPRECISE;natorRD=8.14429;natorP1=0.00274125;natorP2=0;natorP3=0.0209727;natorP4=0;natorQ0=0.829033

[W::vcf_parse] Contig 'III' is not defined in the header. (Quick workaround: index the file with tabix.)
2020-03-18 22:36:54 - svviz2.io.vcfparser       - WARNING - Only tandem duplications are supported; if this duplication is in fact a tandem duplication, make sure that the alt field of the vcf record is '<DUP:TANDEM>': III  8334001 N2_CNVnator_dup_3  N<DUP>   .       PASS    END=8353000;SVTYPE=DUP;SVLEN=19000;IMPRECISE;natorRD=1.96942;natorP1=0.0166545;natorP2=1.18954e+09;natorP3=0.016989;natorP4=1.30514e+09;natorQ0=0.84234

[W::vcf_parse] Contig 'IV' is not defined in the header. (Quick workaround: index the file with tabix.)
))))DEL: Deletion::IV:4,921,000-4,927,999(7000)
2020-03-18 22:36:54 - svviz2.app.datahub        - INFO  - Working on variant 0: Deletion::IV:4,921,000-4,927,999(7000)
2020-03-18 22:36:54 - svviz2.app.datahub        - INFO  - Looking for existing realignments; will try to open a few bam files that may not yet exist...
[E::hts_open_format] Failed to open file /scratch/moldach/data/calls/svviz2-tempxb9wa3f4/N2_CNVnator_del_4.del_IV_4921000.N2_trim_bwaMEM_sort_dedupped.alt.sorted.bam
2020-03-18 22:36:54 - svviz2.app.datahub        - INFO  - Analyzing sample N2_trim_bwaMEM_sort_dedupped
2020-03-18 22:36:54 - svviz2.io.getreads        - INFO  - Loading more read pairs...
2020-03-18 22:36:54 - svviz2.io.getreads        - INFO  - TIME to read batch: 0.0s
2020-03-18 22:36:54 - svviz2.app.datahub        - INFO  - Analyzing 288 read pairs
2020-03-18 22:36:54 - svviz2.app.genomesource   - INFO  - Loading bwa index from file ../references/c_elegans.PRJNA13758.WS274.genomic.fa...
[M::bwa_idx_load_from_disk] read 0 ALT contigs
2020-03-18 22:36:54 - svviz2.app.genomesource   - INFO  - Loading bwa index done.
100%|█████████████████████████████████████████████| 288/288 [00:03<00:00, 84.06it/s]
Reads with only N: 0
REF: 10.95 ALT: 0
TIME::: 4.215909004211426
Traceback (most recent call last):
  File "/scratch/moldach/bin/svviz2-env/bin/svviz2", line 11, in <module>
    load_entry_point('svviz2==2.0a3', 'console_scripts', 'svviz2')()
  File "/scratch/moldach/bin/svviz2-env/lib/python3.7/site-packages/svviz2/app/main.py", line 60, in main
    run(datahub)
  File "/scratch/moldach/bin/svviz2-env/lib/python3.7/site-packages/svviz2/app/main.py", line 46, in run
    visualize.visualize(datahub)
  File "/scratch/moldach/bin/svviz2-env/lib/python3.7/site-packages/svviz2/visualize/visualize.py", line 58, in visualize
    _visualize(datahub)
  File "/scratch/moldach/bin/svviz2-env/lib/python3.7/site-packages/svviz2/visualize/visualize.py", line 76, in _visualize
    genome_view = GenomeView(part.id, start, end, "+", source, name=part.id)
TypeError: __init__() got multiple values for argument 'name'
```

Hope this helps. Let me know if you need any more information and I'll see what I can get.

**Comment by nspies** [comment]
I think you're using a very old version of GenomeView. Can you try updating? 

`pip install --upgrade genomeview`

**Comment by moldach** [comment]
I have version `0.9.1` which seems to be the most up-to-date version:

```
(svviz2) [moldach@cedar5 svviz2]$ pip install --upgrade genomeview
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Requirement already up-to-date: genomeview in /home/moldach/svviz2/lib/python3.7/site-packages (0.9.1)
```

**Comment by nspies** [comment]
Ah, that's it -- you need genomeview >= 1.0. https://pypi.org/project/genomeview/1.0.1/ is the latest released version as of June 25, 2018.

Looks like you're using some non-standard pypi repository.

**Comment by moldach** [comment]
Bringing in the newer version of `genomeview` via `pip install genomeview==1.0.1` causes this error:

```
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview:
  pip install --upgrade --force-reinstall genomeview
```

If I try to run `pip install --upgrade --force-reinstall genomeview` it forces `genomeview` back to version `0.9.0`. Waiting to hear from IT staff at ComputeCanada as to why/if  `pip` is pulling from a *non-standard* pypi repo.
