### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float' [bug]

### ISSUE THREAD

**Issue by jgarces02** [nspies/svviz2#69]
Hi, it seems `numpy` does not have `float` anymore (now it's included in `base`). I had a problem running:

```
$ svviz2 --ref ~/references/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.modified \
	--variants 160023_IGO_15698_6.v2.dellyfiltered.vcf \
	160023_IGO_15698_6.v2.sorted.markdups.bam \
	--outdir tmp

2024-05-28 15:10:05 - svviz2.app.sample         - INFO  - Calculating read statistics for 160023_IGO_15698_6.v2.sorted.markdups.bam
2024-05-28 15:10:05 - svviz2.io.readstatistics  - INFO  -   counts +/-:49132  -/+:869    +/+:0      -/-:0      unpaired:0
2024-05-28 15:10:05 - svviz2.io.readstatistics  - INFO  -   insert size mean: 176.96 std: 49.96 min:19(21) max:340(326)
2024-05-28 15:10:05 - svviz2.io.readstatistics  - INFO  -   discordant: 0.0951
2024-05-28 15:10:05 - svviz2.app.sample         - INFO  - TIME to get read statistics:0.9s
2024-05-28 15:10:05 - svviz2.app.sample         - INFO  - Using realignment presets for illumina
2024-05-28 15:10:05 - svviz2.app.main           - INFO  - Search distance: 335bp
2024-05-28 15:10:05 - svviz2.app.main           - INFO  - Align distance: 493bp
))))DEL: Deletion::chr1:650,692-651,054(363)
2024-05-28 15:10:05 - svviz2.app.datahub        - INFO  - Working on variant 0: Deletion::chr1:650,692-651,054(363)
2024-05-28 15:10:05 - svviz2.app.datahub        - INFO  - Looking for existing realignments; will try to open a few bam files that may not yet exist...
[E::hts_open_format] Failed to open file "tmp/svviz2-tempz18xs3sh/DEL00000000.del_chr1_650692.160023_IGO_15698_6_v2_markdups.alt.sorted.bam" : No such file or directory
2024-05-28 15:10:05 - svviz2.app.datahub        - INFO  - Analyzing sample 160023_IGO_15698_6_v2_markdups
2024-05-28 15:10:05 - svviz2.io.getreads        - INFO  - Loading more read pairs...
2024-05-28 15:10:06 - svviz2.io.getreads        - INFO  - TIME to read batch: 0.0s
2024-05-28 15:10:06 - svviz2.app.datahub        - INFO  - Analyzing 21 read pairs
2024-05-28 15:10:06 - svviz2.app.genomesource   - INFO  - Loading bwa index from file /home/garcesj/references/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.modified...
[M::bwa_idx_load_from_disk] read 0 ALT contigs
2024-05-28 15:10:08 - svviz2.app.genomesource   - INFO  - Loading bwa index done.
  0%|                                                                                                           | 0/21 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/garcesj/software/miniconda3/envs/cfDNA/bin/svviz2", line 8, in <module>
    sys.exit(main())
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/app/main.py", line 60, in main
    run(datahub)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/app/main.py", line 41, in run
    datahub.genotype_cur_variant()
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/app/datahub.py", line 120, in genotype_cur_variant
    aln_sets = maprealign.map_realign(batch, self, sample)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/remap/maprealign.py", line 6, in map_realign
    return map_realign_pairs(batch, realigner, sample)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/remap/maprealign.py", line 23, in map_realign_pairs
    read_or_pair.realign(ref_genome_sources, alt_genome_sources)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/remap/readpair.py", line 57, in realign
    self.ref_pairs = self.realign_against_allele(ref_genome_sources)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/remap/readpair.py", line 51, in realign_against_allele
    self.read_stats.score_read_pair(pair)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/io/readstatistics.py", line 55, in score_read_pair
    insert_size_prob = self.scoreInsertSize(pair.insert_size)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/io/readstatistics.py", line 86, in scoreInsertSize
    self._insertSizeScores[isize] = self._insertSizeKDE(isize)[0]
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/svviz2/utility/kde.py", line 50, in evaluate
    result = zeros((m,), dtype=np.float)
  File "/home/garcesj/software/miniconda3/envs/cfDNA/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

Removing `numpy`'s dependence from this line worked for me --> https://github.com/nspies/svviz2/blob/c86f7a86d8aa39733a637eefc033d0eb4e466869/src/svviz2/utility/kde.py#L50

Thanks.

**Comment by nspies** [comment]
Hi @jgarces02, I'm guessing this line should be `.np.float64`. Happy to accept a PR if you want to confirm this works and submit one.
